#!/bin/bash

HASH="%C(yellow)%h%Creset"
RELATIVE_TIME="%Cgreen(%ar)%Creset"
AUTHOR="%C(bold blue)%an%Creset"
REFS="%C(bold red)%d%Creset"
SUBJECT="%s"

FORMAT="$HASH{$AUTHOR{$RELATIVE_TIME{$REFS $SUBJECT"

function show_git_head() {
  pretty_git_log -1
  git show -p --pretty="tformat:"
}

function pretty_git_log() {
  git log --graph --pretty="tformat:$FORMAT" $* |
  # Replace (2 years ago) with (2 years)
  sed -Ee 's/(^[^<]*) ago\)/\1)/' |
  # Replace (2 years, 5 months) with (2 years)
  sed -Ee 's/(^[^<]*), [[:digit:]]+ .*months?\)/\1)/' |
  # Line columns up based on } delimiter
  column -t -s '{' |
  more -RS
}
